# ============================================================================
# ZXHEIFI - CONTENT FILTER (standalone)
# ============================================================================
# GENERATED by desktop-app/export_rsc.py from the same plan the desktop
# app's Configure MikroTik tab runs - edit mikrotik_commands.py, not this.
#
# Adds just this feature to a router that already has the full ZxheiFi
# config (hAP_lite_full_config.rsc / hEX_full_config.rsc or the desktop app):
# it uses that config's zxheifi-lan bridge and ether1 as the WAN.
# Import: /import file-name=content_filter.rsc
# ============================================================================

# ============================================================================
# 1. CONTENT FILTERING
#    Switches the router's DNS to CleanBrowsing Family Filter, forces customers through it, and blocks the DNS-over-TLS bypass.
# ============================================================================
:put "ZxheiFi: Content Filtering"
:do { /ip dns set servers="185.228.168.168,185.228.169.168" allow-remote-requests="yes" } on-error={ :put "  FAILED: Router DNS: CleanBrowsing Family Filter" }
:do { :if ([:len [/ip firewall nat find where comment="zxheifi: force DNS (UDP)"]] = 0) do={ /ip firewall nat add chain="dstnat" action="redirect" to-ports="53" protocol="udp" dst-port="53" in-interface="zxheifi-lan" comment="zxheifi: force DNS (UDP)" } else={ /ip firewall nat set [/ip firewall nat find where comment="zxheifi: force DNS (UDP)"] chain="dstnat" action="redirect" to-ports="53" protocol="udp" dst-port="53" in-interface="zxheifi-lan" comment="zxheifi: force DNS (UDP)" } } on-error={ :put "  FAILED: Force DNS through the router (UDP)" }
:do { :if ([:len [/ip firewall nat find where comment="zxheifi: force DNS (TCP)"]] = 0) do={ /ip firewall nat add chain="dstnat" action="redirect" to-ports="53" protocol="tcp" dst-port="53" in-interface="zxheifi-lan" comment="zxheifi: force DNS (TCP)" } else={ /ip firewall nat set [/ip firewall nat find where comment="zxheifi: force DNS (TCP)"] chain="dstnat" action="redirect" to-ports="53" protocol="tcp" dst-port="53" in-interface="zxheifi-lan" comment="zxheifi: force DNS (TCP)" } } on-error={ :put "  FAILED: Force DNS through the router (TCP)" }
:do { :if ([:len [/ip firewall filter find where comment="zxheifi: block DNS-over-TLS"]] = 0) do={ /ip firewall filter add chain="forward" action="drop" protocol="tcp" dst-port="853" in-interface="zxheifi-lan" comment="zxheifi: block DNS-over-TLS" } else={ /ip firewall filter set [/ip firewall filter find where comment="zxheifi: block DNS-over-TLS"] chain="forward" action="drop" protocol="tcp" dst-port="853" in-interface="zxheifi-lan" comment="zxheifi: block DNS-over-TLS" } } on-error={ :put "  FAILED: Block DNS-over-TLS bypass" }

# Forget the edit-me values so they don't linger in the router's environment.
/system script environment remove [find where name~"^zx"]
:put "ZxheiFi: done. Look above for any FAILED lines."
