# ============================================================================
# ZXHEIFI - GAMING QoS (standalone)
# ============================================================================
# GENERATED by desktop-app/export_rsc.py from the same plan the desktop
# app's Configure MikroTik tab runs - edit mikrotik_commands.py, not this.
#
# Adds just this feature to a router that already has the full ZxheiFi
# config (hAP_lite_full_config.rsc / hEX_full_config.rsc or the desktop app):
# it uses that config's zxheifi-lan bridge and ether1 as the WAN.
# Import: /import file-name=gaming_qos_fq_codel.rsc
# ============================================================================

# ---- EDIT THESE -------------------------------------------------------------
:global zxDown "70M"
#   ^ ~90% of your real download speed
:global zxUp "20M"
#   ^ ~90% of your real upload speed

# ============================================================================
# 1. GAMING QOS
#    Shapes traffic to your Bandwidth Down/Up and lets game traffic go first. Set those two fields to ~90% of your real internet speed.
# ============================================================================
:put "ZxheiFi: Gaming QoS"
:do { /queue tree remove [/queue tree find where name="gaming-priority"] } on-error={ :put "  FAILED: Remove old queue tree 'gaming-priority'" }
:do { /queue tree remove [/queue tree find where name="default-traffic"] } on-error={ :put "  FAILED: Remove old queue tree 'default-traffic'" }
:do { :if ([:len [/queue type find where name="zxheifi-fq-codel"]] = 0) do={ /queue type add name="zxheifi-fq-codel" kind="fq-codel" fq-codel-ecn="no" fq-codel-target="5ms" fq-codel-interval="100ms" fq-codel-quantum="1514" } else={ /queue type set [/queue type find where name="zxheifi-fq-codel"] name="zxheifi-fq-codel" kind="fq-codel" fq-codel-ecn="no" fq-codel-target="5ms" fq-codel-interval="100ms" fq-codel-quantum="1514" } } on-error={ :put "  FAILED: fq-codel queue type" }
:do { :if ([:len [/ip firewall mangle find where comment="zxheifi: gaming UDP (consoles/PC)"]] = 0) do={ /ip firewall mangle add chain="prerouting" action="mark-packet" new-packet-mark="gaming-udp" passthrough="no" protocol="udp" dst-port="3074,3478-3479,12000-12099,27000-27030,30000-30099" comment="zxheifi: gaming UDP (consoles/PC)" } else={ /ip firewall mangle set [/ip firewall mangle find where comment="zxheifi: gaming UDP (consoles/PC)"] chain="prerouting" action="mark-packet" new-packet-mark="gaming-udp" passthrough="no" protocol="udp" dst-port="3074,3478-3479,12000-12099,27000-27030,30000-30099" comment="zxheifi: gaming UDP (consoles/PC)" } } on-error={ :put "  FAILED: Mark gaming UDP (consoles/PC)" }
:do { :if ([:len [/ip firewall mangle find where comment="zxheifi: gaming UDP return (consoles/PC)"]] = 0) do={ /ip firewall mangle add chain="postrouting" action="mark-packet" new-packet-mark="gaming-udp" passthrough="no" protocol="udp" src-port="3074,3478-3479,12000-12099,27000-27030,30000-30099" comment="zxheifi: gaming UDP return (consoles/PC)" } else={ /ip firewall mangle set [/ip firewall mangle find where comment="zxheifi: gaming UDP return (consoles/PC)"] chain="postrouting" action="mark-packet" new-packet-mark="gaming-udp" passthrough="no" protocol="udp" src-port="3074,3478-3479,12000-12099,27000-27030,30000-30099" comment="zxheifi: gaming UDP return (consoles/PC)" } } on-error={ :put "  FAILED: Mark gaming UDP return (consoles/PC)" }
:do { :if ([:len [/ip firewall mangle find where comment="zxheifi: gaming UDP (mobile, approx range)"]] = 0) do={ /ip firewall mangle add chain="prerouting" action="mark-packet" new-packet-mark="gaming-udp" passthrough="no" protocol="udp" dst-port="5000-9999,13000-19999,21000-26999" comment="zxheifi: gaming UDP (mobile, approx range)" } else={ /ip firewall mangle set [/ip firewall mangle find where comment="zxheifi: gaming UDP (mobile, approx range)"] chain="prerouting" action="mark-packet" new-packet-mark="gaming-udp" passthrough="no" protocol="udp" dst-port="5000-9999,13000-19999,21000-26999" comment="zxheifi: gaming UDP (mobile, approx range)" } } on-error={ :put "  FAILED: Mark gaming UDP (mobile, approx range)" }
:do { :if ([:len [/ip firewall mangle find where comment="zxheifi: gaming UDP return (mobile, approx range)"]] = 0) do={ /ip firewall mangle add chain="postrouting" action="mark-packet" new-packet-mark="gaming-udp" passthrough="no" protocol="udp" src-port="5000-9999,13000-19999,21000-26999" comment="zxheifi: gaming UDP return (mobile, approx range)" } else={ /ip firewall mangle set [/ip firewall mangle find where comment="zxheifi: gaming UDP return (mobile, approx range)"] chain="postrouting" action="mark-packet" new-packet-mark="gaming-udp" passthrough="no" protocol="udp" src-port="5000-9999,13000-19999,21000-26999" comment="zxheifi: gaming UDP return (mobile, approx range)" } } on-error={ :put "  FAILED: Mark gaming UDP return (mobile, approx range)" }
:global zxDown; :do { :if ([:len [/queue tree find where name="zxheifi-down"]] = 0) do={ /queue tree add name="zxheifi-down" parent="zxheifi-lan" max-limit=$zxDown comment="zxheifi" } else={ /queue tree set [/queue tree find where name="zxheifi-down"] name="zxheifi-down" parent="zxheifi-lan" max-limit=$zxDown comment="zxheifi" } } on-error={ :put "  FAILED: Download cap" }
:do { :if ([:len [/queue tree find where name="zxheifi-down-gaming"]] = 0) do={ /queue tree add name="zxheifi-down-gaming" parent="zxheifi-down" packet-mark="gaming-udp" priority="1" queue="zxheifi-fq-codel" comment="zxheifi" } else={ /queue tree set [/queue tree find where name="zxheifi-down-gaming"] name="zxheifi-down-gaming" parent="zxheifi-down" packet-mark="gaming-udp" priority="1" queue="zxheifi-fq-codel" comment="zxheifi" } } on-error={ :put "  FAILED: Download: gaming first" }
:do { :if ([:len [/queue tree find where name="zxheifi-down-other"]] = 0) do={ /queue tree add name="zxheifi-down-other" parent="zxheifi-down" packet-mark="no-mark" priority="8" queue="zxheifi-fq-codel" comment="zxheifi" } else={ /queue tree set [/queue tree find where name="zxheifi-down-other"] name="zxheifi-down-other" parent="zxheifi-down" packet-mark="no-mark" priority="8" queue="zxheifi-fq-codel" comment="zxheifi" } } on-error={ :put "  FAILED: Download: everything else" }
:global zxUp; :do { :if ([:len [/queue tree find where name="zxheifi-up"]] = 0) do={ /queue tree add name="zxheifi-up" parent="ether1" max-limit=$zxUp comment="zxheifi" } else={ /queue tree set [/queue tree find where name="zxheifi-up"] name="zxheifi-up" parent="ether1" max-limit=$zxUp comment="zxheifi" } } on-error={ :put "  FAILED: Upload cap" }
:do { :if ([:len [/queue tree find where name="zxheifi-up-gaming"]] = 0) do={ /queue tree add name="zxheifi-up-gaming" parent="zxheifi-up" packet-mark="gaming-udp" priority="1" queue="zxheifi-fq-codel" comment="zxheifi" } else={ /queue tree set [/queue tree find where name="zxheifi-up-gaming"] name="zxheifi-up-gaming" parent="zxheifi-up" packet-mark="gaming-udp" priority="1" queue="zxheifi-fq-codel" comment="zxheifi" } } on-error={ :put "  FAILED: Upload: gaming first" }
:do { :if ([:len [/queue tree find where name="zxheifi-up-other"]] = 0) do={ /queue tree add name="zxheifi-up-other" parent="zxheifi-up" packet-mark="no-mark" priority="8" queue="zxheifi-fq-codel" comment="zxheifi" } else={ /queue tree set [/queue tree find where name="zxheifi-up-other"] name="zxheifi-up-other" parent="zxheifi-up" packet-mark="no-mark" priority="8" queue="zxheifi-fq-codel" comment="zxheifi" } } on-error={ :put "  FAILED: Upload: everything else" }

# Forget the edit-me values so they don't linger in the router's environment.
/system script environment remove [find where name~"^zx"]
:put "ZxheiFi: done. Look above for any FAILED lines."
