# ============================================================================
# ZXHEIFI - PPPoE SERVER (standalone)
# ============================================================================
# GENERATED by desktop-app/export_rsc.py from the same plan the desktop
# app's Configure MikroTik tab runs - edit mikrotik_commands.py, not this.
#
# Adds just this feature to a router that already has the full ZxheiFi
# config (hAP_lite_full_config.rsc / hEX_full_config.rsc or the desktop app):
# it uses that config's zxheifi-lan bridge and ether1 as the WAN.
# Import: /import file-name=pppoe_server_setup.rsc
# ============================================================================

# ============================================================================
# 1. PPPOE SERVER
#    Optional subscriber PPPoE mode - uses a port marked "PPPoE" if any, otherwise shares the hotspot interface.
# ============================================================================
:put "ZxheiFi: PPPoE Server"
:do { :if ([:len [/ip pool find where name="zxheifi-pppoe-pool"]] = 0) do={ /ip pool add name="zxheifi-pppoe-pool" ranges="10.0.10.10-10.0.10.200" } else={ /ip pool set [/ip pool find where name="zxheifi-pppoe-pool"] name="zxheifi-pppoe-pool" ranges="10.0.10.10-10.0.10.200" } } on-error={ :put "  FAILED: PPPoE address pool" }
:do { :if ([:len [/ppp profile find where name="pppoe-default"]] = 0) do={ /ppp profile add name="pppoe-default" rate-limit="5M/10M" local-address="10.0.10.1" remote-address="zxheifi-pppoe-pool" dns-server="10.0.10.1" use-compression="yes" use-encryption="yes" use-mpls="no" only-one="yes" comment="zxheifi" } else={ /ppp profile set [/ppp profile find where name="pppoe-default"] name="pppoe-default" rate-limit="5M/10M" local-address="10.0.10.1" remote-address="zxheifi-pppoe-pool" dns-server="10.0.10.1" use-compression="yes" use-encryption="yes" use-mpls="no" only-one="yes" comment="zxheifi" } } on-error={ :put "  FAILED: PPPoE speed profile 1" }
:do { :if ([:len [/ppp profile find where name="pppoe-gaming"]] = 0) do={ /ppp profile add name="pppoe-gaming" rate-limit="10M/30M" local-address="10.0.10.1" remote-address="zxheifi-pppoe-pool" dns-server="10.0.10.1" use-compression="yes" use-encryption="yes" use-mpls="no" only-one="yes" comment="zxheifi" } else={ /ppp profile set [/ppp profile find where name="pppoe-gaming"] name="pppoe-gaming" rate-limit="10M/30M" local-address="10.0.10.1" remote-address="zxheifi-pppoe-pool" dns-server="10.0.10.1" use-compression="yes" use-encryption="yes" use-mpls="no" only-one="yes" comment="zxheifi" } } on-error={ :put "  FAILED: PPPoE speed profile 2" }
:do { :if ([:len [/ppp profile find where name="pppoe-high"]] = 0) do={ /ppp profile add name="pppoe-high" rate-limit="20M/50M" local-address="10.0.10.1" remote-address="zxheifi-pppoe-pool" dns-server="10.0.10.1" use-compression="yes" use-encryption="yes" use-mpls="no" only-one="yes" comment="zxheifi" } else={ /ppp profile set [/ppp profile find where name="pppoe-high"] name="pppoe-high" rate-limit="20M/50M" local-address="10.0.10.1" remote-address="zxheifi-pppoe-pool" dns-server="10.0.10.1" use-compression="yes" use-encryption="yes" use-mpls="no" only-one="yes" comment="zxheifi" } } on-error={ :put "  FAILED: PPPoE speed profile 3" }
:do { :if ([:len [/interface pppoe-server server find where service-name="ZxheiFi-PPPoE"]] = 0) do={ /interface pppoe-server server add service-name="ZxheiFi-PPPoE" interface="zxheifi-lan" default-profile="pppoe-default" authentication="pap,chap,mschap1,mschap2" one-session-per-host="yes" max-sessions="50" keepalive-timeout="60" disabled="no" } else={ /interface pppoe-server server set [/interface pppoe-server server find where service-name="ZxheiFi-PPPoE"] service-name="ZxheiFi-PPPoE" interface="zxheifi-lan" default-profile="pppoe-default" authentication="pap,chap,mschap1,mschap2" one-session-per-host="yes" max-sessions="50" keepalive-timeout="60" disabled="no" } } on-error={ :put "  FAILED: PPPoE server" }

# Forget the edit-me values so they don't linger in the router's environment.
/system script environment remove [find where name~"^zx"]
:put "ZxheiFi: done. Look above for any FAILED lines."
