"""
guide_content.py - static text for the in-app Guide tab (main.py's
GuideTab), in two languages. Kept as data separate from the
widget-building code so the walkthrough can be edited without touching
layout code.

SECTIONS_TL (Filipino/Taglish) and SECTIONS_EN (English) must keep the
same section order - the Guide tab's language switch shows one or the
other. When you change one, change the other.
"""

SECTIONS_TL = [
    (
        "Simula Dito",
        "Ang ZxheiFi Setup Companion (v2.0.0-dev) ay gamit para sa PAG-SETUP ng "
        "isang coin-op/voucher WiFi unit - hindi ito ang ginagamit ng customer "
        "(yun ay ang login page na nasa MikroTik). Gamit MO ito (o ng "
        "technician) para i-flash ang NodeMCU, i-configure ang MikroTik at "
        "i-upload ang portal.\n\n"
        "Ano ang ginagawa ng bawat piyesa:\n"
        "• MikroTik (hAP lite / hEX) - ang network: WiFi, login page, "
        "firewall, bilis ng bawat customer.\n"
        "• NodeMCU (ESP8266) - ang negosyo: coin slot, vouchers, oras ng "
        "bawat customer, sales, Admin Dashboard.\n\n"
        "Sunud-sunod:\n"
        "1. I-flash ang firmware sa NodeMCU (tab na 'Flash Firmware').\n"
        "2. I-configure ang MikroTik (tab na 'Configure MikroTik').\n"
        "3. I-click ang 'Upload GUI Files' (kasama na ang sounds).\n"
        "4. I-setup ang NodeMCU gamit ang Setup Wizard nito (phone lang).\n"
        "5. Admin Dashboard: gumawa ng Speed at Rate Profiles.\n"
        "6. Subukan gamit ang phone: voucher at coin.\n\n"
        "BABALA: GAMITIN ANG HIWALAY NA ROUTER. Huwag i-configure ang router na "
        "ginagamit ng bahay/shop mo ngayon - papalitan ng Config ang firewall, "
        "DHCP at DNS nito. Habang nagse-setup, ang PC ay dapat nakakabit LANG "
        "sa router na ise-setup (i-off muna ang WiFi ng PC at tanggalin ang "
        "ibang LAN cable).\n\n"
        "Language: pindutin ang 'English' sa itaas para sa English na bersyon."
    ),
    (
        "Hakbang 1: I-flash ang NodeMCU Firmware",
        "Sa tab na 'Flash Firmware':\n\n"
        "• COM Port - piliin ang USB port ng NodeMCU (hal. 'COM5 - USB-SERIAL "
        "CH340'). Nasa itaas ang mga USB port; ang may 'Bluetooth' ay HINDI "
        "NodeMCU. 'Refresh' kung wala pa.\n\n"
        "• Scan Device - babasahin ang MAC (at IP kung meron) ng NodeMCU, "
        "10-30 segundo. Pindutin ulit ('Cancel Scan') para itigil. Hindi "
        "kailangang mag-scan bago mag-flash - kusang nakukuha ang MAC habang "
        "nagfa-flash, at awtomatiko itong napupunta sa Configure MikroTik tab.\n\n"
        "• Firmware .bin - default na ang kasamang zxheifi_firmware.bin "
        "(v2.0.0-dev).\n\n"
        "• Flash Firmware - huwag alisin ang USB habang nagfa-flash. "
        "Magre-reboot ang NodeMCU pagkatapos. Sa normal na flash, firmware "
        "LANG ang napapalitan - naiiwan ang setup, admin accounts, vouchers, "
        "sales at logs.\n\n"
        "• Erase everything first (fresh start) - burahin LAHAT bago mag-flash "
        "(parang bagong NodeMCU). Lalabas ulit ang \"ZxheiFi-Setup\" WiFi para "
        "sa Setup Wizard. Kusang na-a-uncheck ito pagkatapos ng isang flash.\n\n"
        "• Start Serial Monitor - makikita ang sinasabi ng NodeMCU habang "
        "tumatakbo. Kapag maayos: 'WiFi connected, IP: 10.0.0.254' at "
        "'SYSTEM READY'. Isara ang monitor bago mag-flash ulit.\n\n"
        "MAHALAGA: tuwing may bagong version ng app, i-flash ulit ang NodeMCU "
        "AT i-Upload GUI Files ulit - dapat magkapareho ang version nila. Kapag "
        "luma ang firmware, may pulang banner sa Admin Dashboard."
    ),
    (
        "Hakbang 2: I-configure ang MikroTik",
        "A. IHANDA ANG ROUTER (isang beses lang):\n"
        "1. Winbox → System → Reset Configuration → i-check ang 'No Default "
        "Configuration' → Reset. Pagbalik, kumonekta sa Winbox gamit ang MAC "
        "address (Neighbors tab), hindi IP.\n"
        "2. New Terminal → i-type:\n"
        "   /ip address add address=192.168.88.1/24 interface=ether2\n"
        "3. hAP lite na RouterOS 7: i-install ang 'hotspot' package "
        "(i-drag ang hotspot .npk galing mikrotik.com - kaparehong version at "
        "'mipsbe' - sa Winbox → Files) tapos reboot.\n"
        "4. Device-mode: maraming bagong RouterOS 7 ang naka-'home' mode na "
        "BAWAL ang hotspot at scheduler. Sasabihin ito ng Test Connection at "
        "ibibigay ang command:\n"
        "   /system device-mode update hotspot=yes scheduler=yes\n"
        "   Tapos, within 5 minutes, hugutin ang power ng router nang 5 "
        "segundo at isaksak ulit (o i-TAP nang isang beses ang reset button - "
        "HUWAG i-hold). Test Connection ulit pagkatapos.\n\n"
        "B. IHANDA ANG PC:\n"
        "Isaksak ang PC sa ether2. Walang DHCP ang router na bagong-reset, kaya "
        "lagyan ng fixed IP ang Ethernet ng PC. PowerShell bilang "
        "Administrator (right-click → Run as administrator):\n"
        "   netsh interface ip set address name=\"Ethernet\" static "
        "192.168.88.10 255.255.255.0\n"
        "(Palitan ang \"Ethernet\" kung iba ang pangalan ng adapter.) I-off "
        "muna ang WiFi ng PC.\n\n"
        "C. SA APP:\n"
        "• Router Host = 192.168.88.1, User = admin, Password = password ng "
        "router (hindi ito sine-save ng app).\n"
        "• Test Connection - LAGING UNA. Ipapakita ang pangalan, model at "
        "RouterOS version ng naabot na router - dapat ito yung ise-setup mo. "
        "Pipiliin din nito ang Device at mga port (hAP lite: ether1-4 + wlan1; "
        "hEX: ether1-5, walang WiFi).\n"
        "• WiFi Name / Password - IWANANG BLANGKO ang password para bukas ang "
        "WiFi, gaya ng lahat ng piso WiFi (sa login page nagbabayad).\n"
        "• NodeMCU MAC - nakuha sa Hakbang 1.\n"
        "• NodeMCU API pass - ginawa na ng app, huwag baguhin. Ilalagay mo ito "
        "sa Setup Wizard (Hakbang 4).\n"
        "• Bandwidth Down/Up - mga 90% ng totoong bilis ng internet mo "
        "(hal. 50 Mbps plan → 45M / 9M).\n"
        "• Port Roles - wan (internet), hotspot (may login), lan (walang "
        "login - para sa sarili mong PC; dito ka magse-setup, address "
        "10.0.20.1), pppoe (para sa subscriber na may sariling router).\n"
        "• Features - Base Network, WiFi, Hotspot at NodeMCU API Access ay "
        "laging kasama. Opsyonal ang iba (Gaming QoS, PPPoE, Anti-tethering...).\n"
        "• Config - hihinto kung ibang router ang nakita kaysa sa Test "
        "Connection, kung kulang ang hotspot package, kung bawal ng "
        "device-mode, o kung may ibang setup na ang router (magtatanong "
        "muna). Normal na mag-reconnect nang isang beses. Sa dulo, basahin "
        "ang 'NEXT STEPS'. Pwedeng ulitin - hindi gagawa ng doble.\n"
        "• Remove ZxheiFi Config - tinatanggal LANG ang ginawa ng ZxheiFi.\n\n"
        "Pagkatapos: ibalik ang PC sa automatic IP (Settings → Network → "
        "Ethernet → IP assignment → Automatic), ilipat ang cable ng PC sa "
        "'lan' port, at isaksak ang internet sa ether1.\n\n"
        "MULA NGAYON, huwag nang gamitin ang 192.168.88.1 bilang Router Host - "
        "iyon din ang address ng halos lahat ng MikroTik (pati ang main router "
        "mo). Gamitin ang 10.0.20.1 (PC sa 'lan' port) o 10.0.0.1 (PC sa "
        "hotspot port)."
    ),
    (
        "Hakbang 3: I-upload ang GUI Files",
        "Ang login.html, status.html, admin.html, print.html, style.css, "
        "script.js, logo.png, qrcode.min.js at sounds/ ay ang mga page ng "
        "customer at ng admin - naka-store sa MIKROTIK, hindi sa NodeMCU.\n\n"
        "PINAKAMADALI: pagkatapos ng Config, i-click ang 'Upload GUI Files' sa "
        "Configure MikroTik tab. Ang app na ang:\n"
        "• hahanap ng tamang folder ('hotspot' sa hAP lite, 'flash/hotspot' "
        "sa hEX),\n"
        "• gagawa ng default pages ng MikroTik kung wala pa,\n"
        "• mag-a-upload (FTP ng router - bubuksan saglit kung naka-off, "
        "isasara ulit),\n"
        "• at iche-check kung kumpleto at tama ang size ng bawat file.\n"
        "Ulitin ito tuwing may bagong version.\n\n"
        "MANUAL (kung ayaw gumana ng button):\n"
        "1. Winbox → New Terminal: /ip hotspot reset-html zxheifi-hotspot "
        "(gawin lang kung wala pang folder).\n"
        "2. Winbox → Files → i-drag ang LAHAT ng laman ng GUI folder papunta "
        "sa hotspot folder (tingnan: /ip hotspot profile print → "
        "html-directory). I-overwrite ang mga luma.\n\n"
        "Pagkatapos mag-upload, i-refresh ang page sa phone. Kung luma pa rin "
        "ang itsura: isara at buksan ulit ang browser - kusang ire-reload ng "
        "page ang sarili kapag napansin nitong luma ang naka-cache."
    ),
    (
        "Hakbang 4: Setup Wizard ng NodeMCU",
        "Kapag bago pa (walang naka-save na setup), magbo-broadcast ang "
        "NodeMCU ng WiFi na \"ZxheiFi-Setup\". Ikonekta ang phone dito; "
        "bubukas ang form (o http://192.168.4.1). Ilagay:\n\n"
        "• WiFi name/password - WiFi ng MikroTik (hAP lite) o ng AP mo (hEX). "
        "Kung bukas ang WiFi, iwanang blangko ang password.\n"
        "• MikroTik IP - 10.0.0.1\n"
        "• API user - zxheifi-api\n"
        "• API password - ang 'NodeMCU API pass' sa app (nasa NEXT STEPS).\n"
        "• Admin password - para sa Admin Dashboard. Huwag kalimutan.\n\n"
        "Pagka-save, magre-reboot ito at kokonekta sa MikroTik.\n\n"
        "Para ULITIN ang wizard: i-reset/i-power ang NodeMCU, tapos PINDUTIN "
        "ang FLASH button habang MABILIS na kumukurap ang asul na ilaw (unang "
        "3 segundo pagka-on). Huwag itong pindutin BAGO i-on - papasok sa "
        "flashing mode imbes."
    ),
    (
        "Hakbang 5: Admin Dashboard",
        "Buksan ang http://10.0.0.1/admin.html (nakakonekta sa hotspot WiFi o "
        "sa 'lan' port). Login: user 'admin', password = sa Setup Wizard.\n\n"
        "• Dashboard - kita ngayong araw, active users, status ng MikroTik.\n"
        "• Active Users - Kick (tanggalin) o Block (bawal na ang phone).\n"
        "• Vouchers - piliin ang presyo at ilan → Generate → bubukas ang "
        "printable sheet na may QR, code, ₱, oras, data at 'Valid until' → "
        "Print o Save as PDF. Ang voucher ay nabibilang sa sales kapag "
        "GINAMIT na, hindi kapag ginawa.\n"
        "• Subscriptions - buwanang account (PPPoE/hotspot) na may sariling "
        "speed.\n"
        "• Sales - kita bawat araw (coin/voucher/subscription), piliin ang "
        "petsa (range), Export CSV para sa Excel.\n"
        "• Logs - lahat ng nangyari (login, coin, error).\n"
        "• Settings:\n"
        "  - Announcement - mensaheng lalabas sa login page.\n"
        "  - Speed Profiles - pangalan + Down/Up Mbps (hal. 'Piso 2M' = 2/1). "
        "Unahin ito.\n"
        "  - Rate Profiles - ₱ → minuto, data (0 = walang limit), validity, "
        "speed. Ito ang presyo ng coin AT voucher, at lalabas sa login page "
        "bilang 01d:00H:00M. Gumawa ng isa para sa BAWAT coin na tinatanggap "
        "(₱1, ₱5, ₱10, ₱20).\n"
        "  - Coin Slot - pins at pesos per pulse (tingnan sa ibaba).\n"
        "  - Enable Sounds, branding, Telegram.\n"
        "  - Save Settings - lalabas ang 'Saved' o ang dahilan kung bakit hindi."
    ),
    (
        "Hakbang 6: Subukan gamit ang Phone",
        "1. Kumonekta sa WiFi ng hotspot - dapat lumabas ang login page na may "
        "presyo at announcement.\n"
        "2. VOUCHER: gumawa sa Admin → Vouchers → i-type (o i-scan ang QR) sa "
        "login page → Connect → dapat may internet at status page.\n"
        "3. COIN: 'Insert Coin' → maghulog → 'Done - Connect'.\n"
        "4. Status page: countdown, Pause, Add Time (Coins), Logout.\n"
        "5. Subukan din sa iPhone kung meron - iba ang login browser nito."
    ),
    (
        "Coin Slot",
        "Paano gumagana: pipindutin ng customer ang 'Insert Coin' → "
        "nire-reserve ang coin slot para sa phone niya at bubuksan ang relay → "
        "maghuhulog siya ng coins, makikita ang ₱ at oras → 'Done - Connect' → "
        "naka-login na. Kung makalimutan ang Done, kusang itutuloy pagkalipas "
        "ng 45 segundo na walang bagong coin - hindi masasayang ang pera.\n\n"
        "• Isang customer lang sa isang pagkakataon; ang iba ay sasabihang "
        "maghintay.\n"
        "• Bawat coin ay hinahanapan ng Rate Profile na may EKSAKTONG presyo. "
        "Kapag walang tugma, hindi ito bibilangin at makikita sa Logs "
        "('coin_unmatched').\n\n"
        "Wiring (default): signal ng coin acceptor → D5; relay (power ng "
        "acceptor) → D7; buzzer → D8; magkakabit ang GND ng acceptor, ng 12V "
        "at ng NodeMCU. Kung iba ang baseboard mo: Admin → Settings → Coin "
        "Slot - Coin signal pin (D1/D2/D5/D6/D7), Relay pin (o 'none'), "
        "relay HIGH o LOW (tingnan ang H/L jumper ng relay module), Pesos per "
        "pulse. Gumagana agad pagka-Save, walang restart. Detalye: "
        "docs/11-coin-acceptor-wiring.md."
    ),
    (
        "Sub Vendo (dagdag na coin box)",
        "Ang Sub Vendo ay dagdag na coin box (NodeMCU + coin acceptor) sa ibang "
        "lugar - hal. sa tindahan sa kanto - na nagbebenta ng oras para sa PAREHONG "
        "WiFi. Kokonekta ito sa WiFi ng AP sa lugar na iyon. Ang main unit pa rin "
        "ang bahala sa presyo, oras at sales; taga-bilang lang ng barya ang sub.\n\n"
        "PAGKABIT (isang beses bawat box):\n"
        "1. Admin → Vendos → '+ Add Vendo' → pangalan (hal. 'Tindahan ni Aling "
        "Nena'). Lalabas ang pairing code (hal. K7QM-2XPA-9RTD) - 15 minuto, "
        "isang beses lang magagamit.\n"
        "2. Flash Firmware tab → Device type: 'Sub Vendo' → Flash.\n"
        "3. Sa phone: kumonekta sa WiFi na \"ZxheiFi-Sub-Setup\" → ilagay ang WiFi "
        "ng AP sa lugar na iyon at ang pairing code → Save.\n"
        "4. Sa Admin → Vendos, dapat 🟢 online na ito.\n"
        "5. QR → i-print ang sticker at idikit sa box. Ini-scan ito ng customer "
        "para mapili agad ang box na iyon sa login page.\n\n"
        "ARAW-ARAW:\n"
        "• Makikita sa Vendos ang kita ngayon at laman ng coin box ng bawat isa.\n"
        "• Pagkuha ng barya: pindutin ang 'Collected' - itatala kung sino, kailan "
        "at magkano, at babalik sa ₱0 ang box.\n"
        "• Commission (Edit): parte ng may-ari ng puwesto, hal. 20%. Makikita sa "
        "Sales → piliin ang box, at sa 'Export per-vendo CSV'.\n"
        "• Pins ng sub (Edit): coin pin, relay pin, HIGH/LOW, pesos per pulse - "
        "kusang ipinapadala sa box, walang reflash.\n\n"
        "ILAW NG SUB: dalawang kurap = hindi naka-pair · mabagal = kumokonekta · "
        "tuloy-tuloy = online · mabilis = may naghuhulog · tatlong kurap = hindi "
        "maipadala ang coins (tingnan ang WiFi).\n\n"
        "LIMITASYON: kapag NodeMCU ang main unit, hanggang 3 sub vendo lang (kulang "
        "ang memory nito). Para sa mas marami (hanggang 10) at sa mga susunod na "
        "feature, ESP32 ang gamitin bilang main - darating sa susunod na update.\n\n"
        "KALIGTASAN NG PERA: sarado ang coin slot ng sub kapag hindi nito maabot ang "
        "main nang 3 segundo; ang coin na naipit habang putol ang WiFi ay itinatabi "
        "sa box at ipinapadala pagbalik; walang coin na nabibilang nang dalawang "
        "beses.\n\n"
        "KAPAG MAY PROBLEMA:\n"
        "• Hindi nagpe-pair (dalawang kurap pa rin) → mali o expired ang code: Add "
        "Vendo ulit (o Re-pair), buksan ulit ang wizard (FLASH habang mabilis ang "
        "kurap pagka-on) at ilagay ang bagong code.\n"
        "• 🔴 offline sa Admin → walang WiFi ang box o hindi nito maabot ang main "
        "(dapat nasa parehong network ang AP). Serial Monitor ng sub: 'Pairing' / "
        "'Coin ... acknowledged'.\n"
        "• Customer: 'That coin box is offline' → pumili ng ibang box habang "
        "inaayos.\n"
        "• Nawala/ninakaw ang box → Remove: hindi na ito gagana kahit kailan."
    ),
    (
        "Charging Station (coin-op na charger)",
        "Ang Charging Station ay coin-op na charger ng phone na may 4 na USB port. "
        "Sa box mismo pumipili at nagbabayad ang customer - hindi niya kailangan "
        "ng phone (madalas lowbat nga ito). GUMAGANA KAHIT WALANG WiFi o patay "
        "ang main unit: ang box ang nagpapatakbo ng charging, at bawat bayad ay "
        "itinatabi at ipinapadala sa main kapag may koneksyon na.\n\n"
        "HARDWARE: NodeMCU + coin acceptor (D5) + relay ng acceptor (D7) + "
        "buzzer (D8) + PCF8574 I2C expander (D1/D2: 4 relay ng port + 4 button) "
        "+ maliit na OLED screen (0.96\" SSD1306, opsyonal) + 4-channel relay "
        "module (LOW-trigger) + 5V 10A power supply at fuse bawat port. Detalye: "
        "docs/15-charging-station.md.\n\n"
        "PAGKABIT:\n"
        "1. Admin → Vendos → '+ Add Vendo' → pangalan + Type: 'Charging Station' "
        "→ Create. Lalabas ang pairing code (15 minuto).\n"
        "2. Flash Firmware tab → Device type: 'Charging Station' → Flash.\n"
        "3. Sa phone: WiFi na \"ZxheiFi-Charge-Setup\" → WiFi ng lugar + code → "
        "Save.\n"
        "4. Admin → Settings → Charging: presyo (hal. ₱5 = 30 min, ₱10 = 60 min), "
        "max bawat port (default 3 oras), wika ng screen → Save Settings.\n\n"
        "PAGGAMIT NG CUSTOMER: pindutin ang button ng port → maghulog ng barya "
        "(20 segundo bawat hulog) → tuloy ang charging. Pindutin ulit ang port "
        "para magdagdag ng oras. Kapag walang eksaktong presyo ang barya, "
        "kinukuwenta ito mula sa pinakamurang presyo - walang nasasayang.\n\n"
        "SA ADMIN: makikita sa Vendos ang oras ng bawat port (P1 libre · P2 23m) "
        "at may 'Stop' bawat tumatakbong port. Sa Sales, may column na "
        "'Charging'. May 'Collected' at commission din, gaya ng Sub Vendo.\n\n"
        "BROWNOUT: naka-save ang oras ng bawat port at itutuloy pagbalik ng "
        "kuryente.\n\n"
        "KAPAG MAY PROBLEMA:\n"
        "• Walang lumalabas sa screen → tingnan ang wiring ng OLED (D1/D2, 3.3V, "
        "GND). Gumagana pa rin ang charging kahit walang screen.\n"
        "• Ayaw bumukas ang port / tatlong kurap ang ilaw → hindi makita ang "
        "PCF8574: wiring ng D1/D2, address 0x20 (A0-A2 sa GND).\n"
        "• Tuloy-tuloy na naka-on ang mga port kahit libre → HIGH-trigger ang "
        "relay module: Vendos → Edit → 'Port relays: HIGH'.\n"
        "• '!' sa sulok ng screen → walang koneksyon sa main; tuloy ang charging, "
        "masi-sync ang sales mamaya."
    ),
    (
        "ESP32 Main Unit at Backup",
        "BACKUP / RESTORE (Admin → Settings → Backup & Restore):\n"
        "• 'Download backup' - isang file na may lahat: settings, presyo, vouchers, "
        "subscribers, admin accounts, sales, logs, mga aktibong customer at ang "
        "mga box (kasama ang keys). ITAGO ITO - kung makuha ng iba, puwede "
        "nilang gamitin ang mga box mo. Wala rito ang WiFi at MikroTik password.\n"
        "• 'Restore' - piliin ang file → kumpirmahin → papalitan ang lahat at "
        "magre-restart ang unit. Kapag sira o hindi ZxheiFi ang file, walang "
        "mababago.\n"
        "• Gumawa ng backup paminsan-minsan (hal. linggo-linggo) at bago "
        "mag-flash o magpalit ng board.\n\n"
        "ESP32 BILANG MAIN UNIT (opsyonal - mas malakas na kapalit ng NodeMCU, "
        "hanggang 10 box):\n"
        "1. Sa lumang NodeMCU: Admin → Settings → Download backup.\n"
        "2. Flash Firmware tab → Device type: 'Main unit (ESP32)' → Flash ang "
        "ESP32 DevKit.\n"
        "3. Setup Wizard (\"ZxheiFi-Setup\" WiFi) - parehong sagot tulad ng "
        "dati (WiFi, 10.0.0.1, zxheifi-api, API pass, admin password).\n"
        "4. Configure MikroTik: palitan ang NodeMCU MAC ng MAC ng ESP32 (lalabas "
        "ito habang nagfa-flash) → Config.\n"
        "5. Admin → Settings → Restore → piliin ang backup.\n"
        "6. Pins sa ESP32: coin G14, relay G13, buzzer GPIO25 (BOOT button = "
        "setup). Puwedeng palitan sa Settings → Coin Slot.\n\n"
        "Kapag mali ang board na napili sa Flash tab, hihinto ang flash at "
        "sasabihin kung bakit - walang masisira."
    ),
    (
        "Sounds",
        "Kasama na ang starter set ng sounds (sounds/ folder, na-upload kasama "
        "ng GUI):\n"
        "   • insert-coin.mp3 - \"Please insert your coins now\"\n"
        "   • coin-drop.mp3 - bawat coin  • coin-music.mp3 - tugtog habang "
        "nagbibilang\n"
        "   • success.mp3 - nakakonekta  • error.mp3 - may mali\n"
        "   • click.mp3 - pindot  • background-music.mp3 - sa login page\n\n"
        "Para i-on: Admin → Settings → 'Enable Sounds' → Save.\n\n"
        "Para palitan ng sarili mong tunog: maglagay ng .mp3 na PAREHO ang "
        "pangalan sa sounds/ folder ng GUI (maliit lang - 100-300 KB, 1-2 MB "
        "sa music) tapos Upload GUI Files ulit. Siguraduhing may karapatan kang "
        "gamitin ang musika (walang copyright problem)."
    ),
    (
        "Mga Naranasang Problema at Solusyon",
        "Ito ang mga totoong problemang naranasan habang ginagawa at "
        "tine-test ang ZxheiFi, at kung paano naayos:\n\n"
        "1. 'Invalid password' sa Test Connection at nalo-log out ang Winbox "
        "kahit tama ang password.\n"
        "   Dahilan: napuputol ang Ethernet ng laptop (power saving ng Realtek "
        "network card), kaya sa WiFi dumaan ang PC - papunta sa MAIN router "
        "(hEX) na 192.168.88.1 din ang address.\n"
        "   Solusyon: i-off ang 'Energy Efficient Ethernet', 'Green Ethernet' "
        "at 'Power Saving' ng network card (ibibigay ng Network Check ang "
        "command), i-off ang WiFi ng PC habang nagse-setup, at gamitin ang "
        "10.0.20.1 imbes na 192.168.88.1.\n\n"
        "2. Walang login page / MikroTik WebFig ang lumalabas.\n"
        "   Dahilan: naka-'home' device-mode ang hAP lite - bawal ang hotspot.\n"
        "   Solusyon: /system device-mode update hotspot=yes scheduler=yes, "
        "tapos hugutin ang power within 5 minutes.\n\n"
        "3. '404 Not Found' sa phone.\n"
        "   Dahilan: nasa maling folder ang GUI (hAP lite = 'hotspot', hEX = "
        "'flash/hotspot'), o manual na gumawa ng folder.\n"
        "   Solusyon: Upload GUI Files - ang app na ang pipili ng folder.\n\n"
        "4. 'Detecting...' / Scan na hindi natatapos.\n"
        "   Dahilan: Bluetooth COM port ang napili.\n"
        "   Solusyon: USB-SERIAL (CH340) na port; may Cancel Scan na.\n\n"
        "5. Admin login laging 'Checking...' o mali daw ang password.\n"
        "   Dahilan: offline ang NodeMCU - naka-save pa ang lumang WiFi "
        "password pero bukas na ang WiFi. (At TANDAAN: ang admin password ay "
        "ang sa Setup Wizard, HINDI ang password ng router.)\n"
        "   Solusyon: bagong firmware - kusang kumokonekta sa bukas na WiFi; "
        "may 15 segundong timeout na ang login.\n\n"
        "6. Hindi gumagana ang 'Add Speed Profile' at 'Save Settings'.\n"
        "   Dahilan: lumang naka-cache na script.js sa browser, o lumang "
        "firmware.\n"
        "   Solusyon: may version check na - kusang nire-reload ang page, at "
        "may pulang banner kapag luma ang firmware. I-flash + Upload GUI.\n\n"
        "7. Kumikislap / paulit-ulit na nagpapalit ang URL ng status page.\n"
        "   Dahilan: redirect loop sa pagitan ng login at status.\n"
        "   Solusyon: naayos na sa GUI v1.0.0.\n\n"
        "8. Nashe-share ang WiFi password sa QR ng phone.\n"
        "   Solusyon: bukas na WiFi (walang password) - sa login page "
        "nagbabayad, kaya walang silbi ang pag-share.\n\n"
        "9. Upload GUI 'TimeoutError' / 'didn't check out'.\n"
        "   Dahilan: mabagal ang router habang nagsusulat ng files.\n"
        "   Solusyon: may retry at mas mahabang paghihintay na. Ulitin lang.\n\n"
        "10. hEX na 5 ports pero 4 lang ang lumalabas.\n"
        "   Solusyon: Test Connection muna - ang port list ay galing na sa "
        "totoong board.\n\n"
        "11. Ligtas bang nakasaksak ang internet (galing hEX) sa ether1?\n"
        "   Oo - ang Config ay para LANG sa router na nasa Router Host. Pero "
        "habang nagse-setup, gamitin ang 10.0.20.1 para hindi ang hEX ang "
        "maabot."
    ),
    (
        "Troubleshooting nang Mag-isa",
        "UNANG GAWIN, KAHIT ANO ANG PROBLEMA: Configure MikroTik tab → "
        "'Network Check'. Wala itong binabago at hindi nagla-login - "
        "tinitingnan lang kung saan dumadaan ang PC, kung napuputol ang cable, "
        "ilang MikroTik ang naririnig, at kung nagre-reboot ang router. "
        "Sundin ang mga [!].\n\n"
        "GINTONG PANUNTUNAN: Lahat ng MikroTik ay 192.168.88.1 by default. "
        "Pagkatapos ng Config, gamitin ang 10.0.20.1 ('lan' port) o 10.0.0.1 "
        "(hotspot port). Sa Winbox, kumonekta gamit ang MAC address.\n\n"
        "── PC / KONEKSYON ──\n"
        "• 'Invalid username or password' kahit tama → ibang router ang "
        "naaabot. Network Check.\n"
        "• Winbox nalo-log out / ConnectionResetError / '10 Mbps' → power "
        "saving ng network card o sirang cable.\n"
        "• Test Connection walang sagot → tamang Router Host? tamang port? "
        "IP → Services: naka-enable ang 'api'?\n"
        "• 'Not a direct connection' → sa ibang router dumadaan ang PC.\n\n"
        "── ROUTER ──\n"
        "• 'Hotspot blocked by device-mode' → Hakbang 2A #4.\n"
        "• 'hotspot package is not installed' → Hakbang 2A #3.\n"
        "• WebFig ang lumalabas sa phone → /ip hotspot print - kung may 'I', "
        "device-mode.\n"
        "• '404 not found' → Upload GUI Files ulit.\n"
        "• Router nagre-reboot ('uptime reset') → power adapter.\n\n"
        "── NODEMCU / PORTAL ──\n"
        "• Login page 'Offline' → Serial Monitor: 'WiFi connected, IP: "
        "10.0.0.254'? Tama ba ang NodeMCU MAC noong nag-Config?\n"
        "• 'mikrotik_unreachable' → mali ang API password sa Setup Wizard.\n"
        "• Pulang banner 'firmware outdated' sa Admin → i-flash ang kasamang "
        ".bin.\n"
        "• 'not_saved_low_memory' sa Settings → bawasan ang profiles/"
        "announcement, o i-restart ang NodeMCU at i-Save ulit.\n"
        "• Nakalimutan ang admin password → ulitin ang Setup Wizard, o "
        "'Erase everything first'.\n"
        "• Coin hindi bumibilang → Rate Profile para sa EKSAKTONG halaga? "
        "Tamang Coin pin at Pesos per pulse?\n"
        "• Walang tunog → Enable Sounds; pindutin muna ang screen (bawal sa "
        "phone ang tunog bago may pindot).\n\n"
        "── FLASH FIRMWARE ──\n"
        "• Walang USB port → data cable (hindi charging-only), Refresh.\n"
        "• 'Failed to connect' → hawakan ang FLASH button habang nagsisimula "
        "ang flash, o ibang cable/port.\n\n"
        "Kung wala rito: i-save ang log ng app at ang output ng Network Check "
        "- iyan ang kailangan ng tutulong sa'yo."
    ),
    (
        "Tungkol sa App",
        "ZxheiFi Setup Companion v2.0.0-dev\n\n"
        "Ginawa para gawing madali ang pag-setup ng ZxheiFi coin-op/voucher "
        "WiFi. (Kung manual ang gusto mo, nasa mikrotik/*.rsc ang parehong "
        "setup - basahin ang mikrotik/import_guide.md.)\n\n"
        "Credits: ZxheiFi. Inspired ng JuanFi ni Ivan Julius Alayan "
        "(github.com/ivanalayan15/JuanFi) - ang open-source coin-slot system na "
        "nagsimula ng lahat para sa piso WiFi community. Hiwalay na proyekto "
        "ang ZxheiFi at hindi konektado sa JuanFi.\n\n"
        "MIT License - libre gamitin, i-modify at i-distribute, kahit "
        "pang-negosyo, basta mananatili ang copyright notice (LICENSE). Ang "
        "mga third-party na bahagi ay nasa THIRD-PARTY-NOTICES.md.\n\n"
        "WALANG WARRANTY - i-verify ang setup bago gamitin sa totoong "
        "negosyo. Tingnan ang TERMS.md."
    ),
]


SECTIONS_EN = [
    (
        "Start Here",
        "ZxheiFi Setup Companion (v2.0.0-dev) is for SETTING UP a coin-op/voucher "
        "WiFi unit - it is not what customers use (they use the login page "
        "served by the MikroTik). You (or a technician) use it to flash the "
        "NodeMCU, configure the MikroTik and upload the portal.\n\n"
        "What each part does:\n"
        "• MikroTik (hAP lite / hEX) - the network: WiFi, login page, "
        "firewall, per-customer speed.\n"
        "• NodeMCU (ESP8266) - the business: coin slot, vouchers, customer "
        "time, sales, Admin Dashboard.\n\n"
        "In order:\n"
        "1. Flash the firmware to the NodeMCU ('Flash Firmware' tab).\n"
        "2. Configure the MikroTik ('Configure MikroTik' tab).\n"
        "3. Click 'Upload GUI Files' (sounds included).\n"
        "4. Set up the NodeMCU with its Setup Wizard (phone only).\n"
        "5. Admin Dashboard: create Speed and Rate Profiles.\n"
        "6. Test with a phone: voucher and coin.\n\n"
        "WARNING: USE A SEPARATE ROUTER. Do not configure the router your "
        "home/shop uses today - Config replaces its firewall, DHCP and DNS. "
        "While setting up, the PC must be connected ONLY to the router being "
        "set up (turn the PC's WiFi off and unplug other LAN cables).\n\n"
        "Language: press 'Tagalog' at the top for the Filipino version."
    ),
    (
        "Step 1: Flash the NodeMCU Firmware",
        "In the 'Flash Firmware' tab:\n\n"
        "• COM Port - pick the NodeMCU's USB port (e.g. 'COM5 - USB-SERIAL "
        "CH340'). USB ports are listed first; 'Bluetooth' ports are NOT the "
        "NodeMCU. Press 'Refresh' if it's missing.\n\n"
        "• Scan Device - reads the NodeMCU's MAC (and IP if it has one), "
        "10-30 seconds. Press again ('Cancel Scan') to stop. Scanning before "
        "flashing is optional - the MAC is read during the flash and filled "
        "into the Configure MikroTik tab automatically.\n\n"
        "• Firmware .bin - defaults to the bundled zxheifi_firmware.bin "
        "(v2.0.0-dev).\n\n"
        "• Flash Firmware - don't unplug the USB while flashing. The NodeMCU "
        "reboots afterwards. A normal flash replaces ONLY the firmware - the "
        "setup, admin accounts, vouchers, sales and logs are kept.\n\n"
        "• Erase everything first (fresh start) - wipes EVERYTHING before "
        "flashing (like a new NodeMCU). The \"ZxheiFi-Setup\" WiFi appears "
        "again for the Setup Wizard. It unticks itself after one flash.\n\n"
        "• Start Serial Monitor - shows what the NodeMCU is doing. When "
        "healthy: 'WiFi connected, IP: 10.0.0.254' and 'SYSTEM READY'. Stop "
        "the monitor before flashing again.\n\n"
        "IMPORTANT: whenever you get a new app version, reflash the NodeMCU "
        "AND run Upload GUI Files again - their versions must match. An "
        "outdated firmware shows a red banner in the Admin Dashboard."
    ),
    (
        "Step 2: Configure the MikroTik",
        "A. PREPARE THE ROUTER (once):\n"
        "1. Winbox → System → Reset Configuration → tick 'No Default "
        "Configuration' → Reset. Afterwards, connect in Winbox by MAC address "
        "(Neighbors tab), not IP.\n"
        "2. New Terminal → type:\n"
        "   /ip address add address=192.168.88.1/24 interface=ether2\n"
        "3. hAP lite on RouterOS 7: install the 'hotspot' package (drag the "
        "hotspot .npk from mikrotik.com - same version, 'mipsbe' - into "
        "Winbox → Files) and reboot.\n"
        "4. Device-mode: many new RouterOS 7 units ship in 'home' mode, which "
        "BLOCKS hotspot and scheduler. Test Connection tells you and gives "
        "the command:\n"
        "   /system device-mode update hotspot=yes scheduler=yes\n"
        "   Then, within 5 minutes, unplug the router's power for 5 seconds "
        "and plug it back in (or TAP the reset button once - do NOT hold "
        "it). Run Test Connection again afterwards.\n\n"
        "B. PREPARE THE PC:\n"
        "Plug the PC into ether2. A freshly reset router has no DHCP, so give "
        "the PC's Ethernet a fixed IP. PowerShell as Administrator "
        "(right-click → Run as administrator):\n"
        "   netsh interface ip set address name=\"Ethernet\" static "
        "192.168.88.10 255.255.255.0\n"
        "(Change \"Ethernet\" if your adapter has another name.) Turn the "
        "PC's WiFi off.\n\n"
        "C. IN THE APP:\n"
        "• Router Host = 192.168.88.1, User = admin, Password = the router's "
        "password (the app never saves it).\n"
        "• Test Connection - ALWAYS FIRST. Shows the name, model and RouterOS "
        "version of the router it reached - it must be the one you're setting "
        "up. It also picks the Device and ports (hAP lite: ether1-4 + wlan1; "
        "hEX: ether1-5, no WiFi).\n"
        "• WiFi Name / Password - LEAVE THE PASSWORD BLANK for open WiFi, like "
        "every piso WiFi (customers pay on the login page).\n"
        "• NodeMCU MAC - from Step 1.\n"
        "• NodeMCU API pass - generated by the app, don't change it. You'll "
        "enter it in the Setup Wizard (Step 4).\n"
        "• Bandwidth Down/Up - about 90% of your real internet speed "
        "(e.g. 50 Mbps plan → 45M / 9M).\n"
        "• Port Roles - wan (internet), hotspot (login required), lan (no "
        "login - for your own PC; manage the router here at 10.0.20.1), "
        "pppoe (for subscribers with their own router).\n"
        "• Features - Base Network, WiFi, Hotspot and NodeMCU API Access are "
        "always included. The rest are optional (Gaming QoS, PPPoE, "
        "Anti-tethering...).\n"
        "• Config - stops if it reaches a different router than Test "
        "Connection did, if the hotspot package is missing, if device-mode "
        "blocks it, or if the router already has another setup (it asks "
        "first). Reconnecting once midway is normal. Read the 'NEXT STEPS' at "
        "the end. Safe to repeat - it never creates duplicates.\n"
        "• Remove ZxheiFi Config - removes ONLY what ZxheiFi created.\n\n"
        "Afterwards: set the PC back to automatic IP (Settings → Network → "
        "Ethernet → IP assignment → Automatic), move the PC's cable to the "
        "'lan' port, and plug the internet into ether1.\n\n"
        "FROM NOW ON, don't use 192.168.88.1 as Router Host - almost every "
        "MikroTik (including your main router) uses it. Use 10.0.20.1 (PC on "
        "the 'lan' port) or 10.0.0.1 (PC on a hotspot port)."
    ),
    (
        "Step 3: Upload the GUI Files",
        "login.html, status.html, admin.html, print.html, style.css, "
        "script.js, logo.png, qrcode.min.js and sounds/ are the customer and "
        "admin pages - stored on the MIKROTIK, not the NodeMCU.\n\n"
        "EASIEST: after Config, click 'Upload GUI Files' in the Configure "
        "MikroTik tab. The app will:\n"
        "• find the right folder ('hotspot' on hAP lite, 'flash/hotspot' on "
        "hEX),\n"
        "• create MikroTik's default pages if missing,\n"
        "• upload (via the router's FTP - turned on briefly if it was off, "
        "then restored),\n"
        "• and verify every file is present with the right size.\n"
        "Repeat after every new version.\n\n"
        "MANUAL (if the button fails):\n"
        "1. Winbox → New Terminal: /ip hotspot reset-html zxheifi-hotspot "
        "(only if the folder doesn't exist yet).\n"
        "2. Winbox → Files → drag EVERYTHING from the GUI folder into the "
        "hotspot folder (check: /ip hotspot profile print → html-directory). "
        "Overwrite the old files.\n\n"
        "After uploading, refresh the page on the phone. If it still looks "
        "old: close and reopen the browser - the pages reload themselves when "
        "they detect a stale cached copy."
    ),
    (
        "Step 4: NodeMCU Setup Wizard",
        "When new (no saved setup), the NodeMCU broadcasts a WiFi called "
        "\"ZxheiFi-Setup\". Connect your phone; the form opens (or go to "
        "http://192.168.4.1). Enter:\n\n"
        "• WiFi name/password - the MikroTik's WiFi (hAP lite) or your AP's "
        "(hEX). If the WiFi is open, leave the password blank.\n"
        "• MikroTik IP - 10.0.0.1\n"
        "• API user - zxheifi-api\n"
        "• API password - the 'NodeMCU API pass' from the app (also in NEXT "
        "STEPS).\n"
        "• Admin password - for the Admin Dashboard. Don't forget it.\n\n"
        "After saving, it reboots and connects to the MikroTik.\n\n"
        "To RUN THE WIZARD AGAIN: reset/power the NodeMCU, then PRESS the "
        "FLASH button while the blue light blinks FAST (first 3 seconds after "
        "power-on). Don't hold it BEFORE powering on - that enters flashing "
        "mode instead."
    ),
    (
        "Step 5: Admin Dashboard",
        "Open http://10.0.0.1/admin.html (connected to the hotspot WiFi or "
        "the 'lan' port). Login: user 'admin', password = the one from the "
        "Setup Wizard.\n\n"
        "• Dashboard - today's income, active users, MikroTik status.\n"
        "• Active Users - Kick (disconnect) or Block (ban the device).\n"
        "• Vouchers - choose the price and how many → Generate → a printable "
        "sheet opens with QR, code, ₱, time, data and 'Valid until' → Print "
        "or Save as PDF. A voucher counts as a sale when it is USED, not when "
        "it is created.\n"
        "• Subscriptions - monthly accounts (PPPoE/hotspot) with their own "
        "speed.\n"
        "• Sales - daily income (coin/voucher/subscription), pick a date "
        "range, Export CSV for Excel.\n"
        "• Logs - everything that happened (logins, coins, errors).\n"
        "• Settings:\n"
        "  - Announcement - message shown on the login page.\n"
        "  - Speed Profiles - name + Down/Up Mbps (e.g. 'Piso 2M' = 2/1). Do "
        "these first.\n"
        "  - Rate Profiles - ₱ → minutes, data (0 = unlimited), validity, "
        "speed. This is the price for coins AND vouchers, shown on the login "
        "page as 01d:00H:00M. Make one for EVERY coin your acceptor takes "
        "(₱1, ₱5, ₱10, ₱20).\n"
        "  - Coin Slot - pins and pesos per pulse (see below).\n"
        "  - Enable Sounds, branding, Telegram.\n"
        "  - Save Settings - shows 'Saved' or the reason it couldn't."
    ),
    (
        "Step 6: Test with a Phone",
        "1. Join the hotspot WiFi - the login page should appear with prices "
        "and the announcement.\n"
        "2. VOUCHER: create one in Admin → Vouchers → type it (or scan the "
        "QR) on the login page → Connect → you should get internet and the "
        "status page.\n"
        "3. COIN: 'Insert Coin' → drop coins → 'Done - Connect'.\n"
        "4. Status page: countdown, Pause, Add Time (Coins), Logout.\n"
        "5. Test on an iPhone too if you can - its login browser differs."
    ),
    (
        "Coin Slot",
        "How it works: the customer taps 'Insert Coin' → the coin slot is "
        "reserved for their phone and the relay switches on → they drop "
        "coins and see ₱ and time → 'Done - Connect' → logged in. If they "
        "forget Done, it continues automatically after 45 seconds without a "
        "new coin - no money is lost.\n\n"
        "• One customer at a time; others are asked to wait.\n"
        "• Each coin is matched to a Rate Profile with the EXACT price. With "
        "no match it isn't credited and shows in Logs ('coin_unmatched').\n\n"
        "Wiring (default): coin acceptor signal → D5; relay (acceptor power) → "
        "D7; buzzer → D8; acceptor GND, 12V GND and NodeMCU GND tied together. "
        "Different baseboard? Admin → Settings → Coin Slot - Coin signal pin "
        "(D1/D2/D5/D6/D7), Relay pin (or 'none'), relay HIGH or LOW (check "
        "the relay module's H/L jumper), Pesos per pulse. Takes effect on "
        "Save, no restart. Details: docs/11-coin-acceptor-wiring.md."
    ),
    (
        "Sub Vendo (extra coin box)",
        "A Sub Vendo is an extra coin box (NodeMCU + coin acceptor) somewhere else "
        "- e.g. the store at the corner - that sells time for the SAME WiFi. It "
        "joins the WiFi of the AP at its spot. The main unit still handles prices, "
        "time and sales; the sub only counts coins.\n\n"
        "SETUP (once per box):\n"
        "1. Admin → Vendos → '+ Add Vendo' → a name (e.g. 'Tindahan ni Aling "
        "Nena'). A pairing code appears (e.g. K7QM-2XPA-9RTD) - 15 minutes, one "
        "use.\n"
        "2. Flash Firmware tab → Device type: 'Sub Vendo' → Flash.\n"
        "3. On a phone: join the WiFi \"ZxheiFi-Sub-Setup\" → enter the WiFi of "
        "the AP at that spot and the pairing code → Save.\n"
        "4. Admin → Vendos should now show it 🟢 online.\n"
        "5. QR → print the sticker and put it on the box. Customers scan it and "
        "the login page picks that box for them.\n\n"
        "DAY TO DAY:\n"
        "• Vendos shows today's income and the coin-box contents of each box.\n"
        "• Emptying a box: press 'Collected' - it records who, when and how much, "
        "and resets the box to ₱0.\n"
        "• Commission (Edit): the location host's share, e.g. 20%. See Sales → pick "
        "the box, and 'Export per-vendo CSV'.\n"
        "• Sub pins (Edit): coin pin, relay pin, HIGH/LOW, pesos per pulse - sent "
        "to the box automatically, no reflash.\n\n"
        "SUB LED: double blink = not paired · slow = connecting · solid = online · "
        "fast = someone is inserting · triple blink = coins can't be sent (check "
        "the WiFi).\n\n"
        "LIMITS: with a NodeMCU as the main unit, up to 3 sub vendos (its memory "
        "is small). For more (up to 10) and upcoming features, use an ESP32 as the "
        "main unit - coming in a later update.\n\n"
        "MONEY SAFETY: the sub's coin slot closes when it can't reach the main unit "
        "for 3 seconds; a coin caught while the WiFi is down is kept in the box and "
        "sent when it's back; no coin is ever counted twice.\n\n"
        "IF SOMETHING'S WRONG:\n"
        "• Won't pair (still double blink) → wrong or expired code: Add Vendo "
        "again (or Re-pair), reopen the wizard (FLASH while the LED blinks fast "
        "after power-on) and enter the new code.\n"
        "• 🔴 offline in Admin → the box has no WiFi or can't reach the main unit "
        "(the AP must be on the same network). Sub Serial Monitor: 'Pairing' / "
        "'Coin ... acknowledged'.\n"
        "• Customer sees 'That coin box is offline' → pick another box meanwhile.\n"
        "• Box lost or stolen → Remove: it can never be used again."
    ),
    (
        "Charging Station (coin-op charger)",
        "A Charging Station is a coin-op phone charger with 4 USB ports. The "
        "customer picks a port and pays at the box - no phone needed (it's "
        "usually the flat one). IT WORKS WITHOUT WiFi or with the main unit "
        "down: the box runs the charging itself, and every sale is stored and "
        "sent to the main unit once there's a connection.\n\n"
        "HARDWARE: NodeMCU + coin acceptor (D5) + acceptor relay (D7) + buzzer "
        "(D8) + PCF8574 I2C expander (D1/D2: 4 port relays + 4 buttons) + small "
        "OLED screen (0.96\" SSD1306, optional) + 4-channel relay module "
        "(LOW-trigger) + 5V 10A supply with a fuse per port. Details: "
        "docs/15-charging-station.md.\n\n"
        "SETUP:\n"
        "1. Admin → Vendos → '+ Add Vendo' → name + Type: 'Charging Station' → "
        "Create. A pairing code appears (15 minutes).\n"
        "2. Flash Firmware tab → Device type: 'Charging Station' → Flash.\n"
        "3. On a phone: WiFi \"ZxheiFi-Charge-Setup\" → the WiFi of that spot + "
        "the code → Save.\n"
        "4. Admin → Settings → Charging: prices (e.g. ₱5 = 30 min, ₱10 = 60 min), "
        "max per port (default 3 hours), screen language → Save Settings.\n\n"
        "CUSTOMER USE: press a port's button → drop coins (20 seconds per coin) → "
        "it charges. Press the port again to add time. A coin with no exact "
        "price is worked out from the cheapest price - nothing is wasted.\n\n"
        "IN ADMIN: Vendos shows each port's time (P1 free · P2 23m) with a "
        "'Stop' per running port. Sales has a 'Charging' column. Collected and "
        "commission work like a Sub Vendo.\n\n"
        "POWER CUT: each port's time is saved and resumes when the power is "
        "back.\n\n"
        "IF SOMETHING'S WRONG:\n"
        "• Blank screen → check the OLED wiring (D1/D2, 3.3V, GND). Charging "
        "still works without a screen.\n"
        "• Ports don't switch / triple blink → the PCF8574 isn't found: wiring of "
        "D1/D2, address 0x20 (A0-A2 to GND).\n"
        "• Ports stay on while free → the relay module is HIGH-trigger: Vendos → "
        "Edit → 'Port relays: HIGH'.\n"
        "• '!' in the screen's corner → no link to the main unit; charging goes "
        "on and sales sync later."
    ),
    (
        "ESP32 Main Unit and Backup",
        "BACKUP / RESTORE (Admin → Settings → Backup & Restore):\n"
        "• 'Download backup' - one file with everything: settings, prices, "
        "vouchers, subscribers, admin accounts, sales, logs, live customers and "
        "your coin boxes (with their keys). KEEP IT PRIVATE - with it, someone "
        "could take over your boxes. WiFi and MikroTik passwords are not in it.\n"
        "• 'Restore' - pick the file → confirm → everything is replaced and the "
        "unit restarts. A damaged or foreign file changes nothing.\n"
        "• Make a backup now and then (e.g. weekly) and before flashing or "
        "swapping boards.\n\n"
        "ESP32 AS THE MAIN UNIT (optional - a stronger replacement for the "
        "NodeMCU, up to 10 boxes):\n"
        "1. On the old NodeMCU: Admin → Settings → Download backup.\n"
        "2. Flash Firmware tab → Device type: 'Main unit (ESP32)' → Flash the ESP32 "
        "DevKit.\n"
        "3. Setup Wizard (\"ZxheiFi-Setup\" WiFi) - same answers as before (WiFi, "
        "10.0.0.1, zxheifi-api, API pass, admin password).\n"
        "4. Configure MikroTik: replace the NodeMCU MAC with the ESP32's MAC (shown "
        "while flashing) → Config.\n"
        "5. Admin → Settings → Restore → pick the backup.\n"
        "6. ESP32 pins: coin G14, relay G13, buzzer GPIO25 (BOOT button = setup). "
        "Changeable in Settings → Coin Slot.\n\n"
        "If the wrong board is chosen in the Flash tab, the flash stops and says "
        "why - nothing is damaged."
    ),
    (
        "Sounds",
        "A starter sound set is included (sounds/ folder, uploaded with the "
        "GUI):\n"
        "   • insert-coin.mp3 - \"Please insert your coins now\"\n"
        "   • coin-drop.mp3 - each coin  • coin-music.mp3 - music while "
        "counting\n"
        "   • success.mp3 - connected  • error.mp3 - something went wrong\n"
        "   • click.mp3 - button press  • background-music.mp3 - login page\n\n"
        "To turn on: Admin → Settings → 'Enable Sounds' → Save.\n\n"
        "To use your own: put an .mp3 with the SAME name in the GUI's sounds/ "
        "folder (keep it small - 100-300 KB, 1-2 MB for music) and run Upload "
        "GUI Files again. Make sure you have the right to use the music."
    ),
    (
        "Problems We Hit and How They Were Fixed",
        "Real problems met while building and testing ZxheiFi, and their "
        "fixes:\n\n"
        "1. 'Invalid password' on Test Connection and Winbox logging out even "
        "with the right password.\n"
        "   Cause: the laptop's Ethernet kept dropping (Realtek power "
        "saving), so traffic went over WiFi - to the MAIN router (hEX), "
        "which is also 192.168.88.1.\n"
        "   Fix: turn off 'Energy Efficient Ethernet', 'Green Ethernet' and "
        "'Power Saving' on the network card (Network Check gives the "
        "commands), turn the PC's WiFi off while setting up, and use "
        "10.0.20.1 instead of 192.168.88.1.\n\n"
        "2. No login page / MikroTik WebFig appears instead.\n"
        "   Cause: the hAP lite was in 'home' device-mode - hotspot blocked.\n"
        "   Fix: /system device-mode update hotspot=yes scheduler=yes, then "
        "unplug the power within 5 minutes.\n\n"
        "3. '404 Not Found' on the phone.\n"
        "   Cause: GUI in the wrong folder (hAP lite = 'hotspot', hEX = "
        "'flash/hotspot'), or a folder created by hand.\n"
        "   Fix: Upload GUI Files - the app picks the folder.\n\n"
        "4. 'Detecting...' / a scan that never ends.\n"
        "   Cause: a Bluetooth COM port was selected.\n"
        "   Fix: pick the USB-SERIAL (CH340) port; Cancel Scan now exists.\n\n"
        "5. Admin login stuck on 'Checking...' or says the password is "
        "wrong.\n"
        "   Cause: the NodeMCU was offline - it still had the old WiFi "
        "password saved but the WiFi was now open. (And REMEMBER: the admin "
        "password is the Setup Wizard one, NOT the router's password.)\n"
        "   Fix: new firmware joins open WiFi automatically; login now times "
        "out after 15 seconds.\n\n"
        "6. 'Add Speed Profile' and 'Save Settings' did nothing.\n"
        "   Cause: an old cached script.js in the browser, or old firmware.\n"
        "   Fix: version checks - the page reloads itself, and a red banner "
        "shows when the firmware is outdated. Flash + Upload GUI.\n\n"
        "7. The status page URL flickering / changing over and over.\n"
        "   Cause: a redirect loop between login and status.\n"
        "   Fix: solved in GUI v1.0.0.\n\n"
        "8. The WiFi password could be shared through the phone's QR.\n"
        "   Fix: open WiFi (no password) - customers pay on the login page, "
        "so sharing gains nothing.\n\n"
        "9. Upload GUI 'TimeoutError' / 'didn't check out'.\n"
        "   Cause: the router is slow while writing files.\n"
        "   Fix: retries and longer waits added. Just run it again.\n\n"
        "10. hEX has 5 ports but only 4 were shown.\n"
        "   Fix: run Test Connection first - the port list now comes from the "
        "real board.\n\n"
        "11. Is it safe to have the internet (from the hEX) plugged into "
        "ether1?\n"
        "   Yes - Config only touches the router at Router Host. While "
        "setting up, use 10.0.20.1 so the hEX isn't reached by mistake."
    ),
    (
        "Troubleshooting on Your Own",
        "FIRST, WHATEVER THE PROBLEM: Configure MikroTik tab → 'Network "
        "Check'. It changes nothing and doesn't log in - it only checks which "
        "way the PC reaches the router, whether the cable drops, how many "
        "MikroTiks answer, and whether the router is rebooting. Follow the "
        "[!] lines.\n\n"
        "GOLDEN RULE: every MikroTik is 192.168.88.1 by default. After Config, "
        "use 10.0.20.1 ('lan' port) or 10.0.0.1 (hotspot port). In Winbox, "
        "connect by MAC address.\n\n"
        "── PC / CONNECTION ──\n"
        "• 'Invalid username or password' although correct → a different "
        "router is being reached. Network Check.\n"
        "• Winbox logs out / ConnectionResetError / '10 Mbps' → network card "
        "power saving or a bad cable.\n"
        "• Test Connection doesn't answer → right Router Host? right port? "
        "IP → Services: is 'api' enabled?\n"
        "• 'Not a direct connection' → the PC goes through another router.\n\n"
        "── ROUTER ──\n"
        "• 'Hotspot blocked by device-mode' → Step 2A #4.\n"
        "• 'hotspot package is not installed' → Step 2A #3.\n"
        "• WebFig appears on the phone → /ip hotspot print - an 'I' means "
        "device-mode.\n"
        "• '404 not found' → Upload GUI Files again.\n"
        "• Router rebooting ('uptime reset') → power adapter.\n\n"
        "── NODEMCU / PORTAL ──\n"
        "• Login page 'Offline' → Serial Monitor: 'WiFi connected, IP: "
        "10.0.0.254'? Was the NodeMCU MAC right during Config?\n"
        "• 'mikrotik_unreachable' → wrong API password in the Setup Wizard.\n"
        "• Red 'firmware outdated' banner in Admin → flash the bundled .bin.\n"
        "• 'not_saved_low_memory' in Settings → fewer profiles/shorter "
        "announcement, or restart the NodeMCU and Save again.\n"
        "• Forgot the admin password → run the Setup Wizard again, or "
        "'Erase everything first'.\n"
        "• Coins not counted → a Rate Profile for the EXACT value? Right Coin "
        "pin and Pesos per pulse?\n"
        "• No sound → Enable Sounds; tap the screen first (phones block "
        "sound until the user taps).\n\n"
        "── FLASH FIRMWARE ──\n"
        "• No USB port → use a data cable (not charge-only), Refresh.\n"
        "• 'Failed to connect' → hold the FLASH button as flashing starts, or "
        "try another cable/port.\n\n"
        "Not listed here? Save the app's log and the Network Check output - "
        "that's what anyone helping you will need."
    ),
    (
        "About",
        "ZxheiFi Setup Companion v2.0.0-dev\n\n"
        "Built to make setting up ZxheiFi coin-op/voucher WiFi easy. (Prefer "
        "manual? The same setup is in mikrotik/*.rsc - see "
        "mikrotik/import_guide.md.)\n\n"
        "Credits: ZxheiFi. Inspired by JuanFi by Ivan Julius Alayan "
        "(github.com/ivanalayan15/JuanFi) - the open-source coin-slot system "
        "that started it all for the piso WiFi community. ZxheiFi is an "
        "independent project, not affiliated with JuanFi.\n\n"
        "MIT License - free to use, modify and distribute, including "
        "commercially, as long as the copyright notice stays (LICENSE). "
        "Third-party parts are listed in THIRD-PARTY-NOTICES.md.\n\n"
        "NO WARRANTY - verify the setup before using it in a real business. "
        "See TERMS.md."
    ),
]

# Backwards-compatible name (the Guide defaults to Tagalog).
SECTIONS = SECTIONS_TL
LANGUAGES = {"tl": ("Tagalog", SECTIONS_TL), "en": ("English", SECTIONS_EN)}
